import sys
import os

base_dir = '/home/ajai-krishna/work/Greenipath/Data-analysis_and_reporting_end-to-end/src'
data_dir = '/home/ajai-krishna/work/Greenipath/Data-analysis_and_reporting_end-to-end/src/Data/'
output_dir = os.path.join(data_dir,"Outputs")
meta_dir = os.path.join(f'{output_dir}/Meta_data')
output_gis_validation = os.path.join(f'{output_dir}/Gis-validations')
data_overview_out = os.path.join(f'{output_dir}/Data_overview')
try:
    os.makedirs(output_dir, exist_ok=True)
except (PermissionError, OSError):
    pass

data1 = os.path.join(data_dir,"20250605_Makkala_Vikasa_Master_Sheet (1) (1).xlsx")
data2 = os.path.join(data_dir,"20260507_YIDS_Approved sheet (1) (1).xlsx")
master_df = os.path.join(f'{output_dir}/master_Database.xlsx')
master_cleaned_df = os.path.join(f'{output_dir}/master_Database_cleaned.xlsx')
kml_data = os.path.join(data_dir,"20260507_YIDS_MasterKML_Filtered (1) (2).kmz") 
kml_master_data = os.path.join(data_dir,"doc.kml")


# survey_df = meta_dfs["survey"]
# location_df = meta_dfs["location"]
# tree_inventory_df = meta_dfs["tree_inventory"]
# farmer_df = meta_dfs["farmer"]
# location_df = meta_dfs["location"]
# tree_category_df = meta_dfs["tree_category"]
# participant_category_df = meta_dfs["participant_category"]
# plantation_df = meta_dfs["plantation"]
# tree_inventory_df=meta_dfs["tree_inventory"]
# media_df= meta_dfs["media"]
# gis_df= meta_dfs["gis"]
# other_tree_df= meta_dfs["other_tree"]
# unnamed_df = meta_dfs["unnamed"]
# others_df = meta_dfs["others"]


column_mapping = {
    "Surveyor_Name": ["Surveryor_s_Name","Surveyor_name"],

    "Farmer_Name": ["Farmer_s_Name","Farmer_name"],

    "Farmer_Mobile": ["Farmer_s_Mobile_Number","Farmer's_Mobile_number"],

    "Block_Name": ["Block_Name","Block_name"],

    "Gram_Panchayat": ["Gram_Panachayat_Name","GP_Name"],

    "Village_Name": ["Village_Name"],

    "Irrigation": ["Irrigation_land","Irrigation land"],

    "Intercropping": ["Intercropping","Intercroping"],

    "Latitude": ["_Record_your_current_location_latitude","_Record your current location_latitude"],

    "Longitude": ["_Record_your_current_location_longitude","_Record your current location_longitude"],

    "Current_Location": ["Record_your_current_location","Record your current location"],

    "Notes": ["_notes","_Notes"],

    "Claimed_Area": ["Claimed area","Claimed area (acre)"],

    "Actual_Area": ["Actual area","Actual area (acrea)"],

    "Remarks": ["Remarks","Remarks for KML"]
}
village_mapping = {
    # A: Variations → Standard forms
    "Anikere": "Anekere", "Anikera": "Anekere", "Aniker": "Anekere", "Anikeri": "Anekere",
    "Acchampalli": "Adampalli", "Abani": "Abbani", "Abni": "Abbani", "Absni": "Abbani",
    "Abehalli": "Arehalli", "Agnihalli": "Angnihalli", "Annihalli": "Angnihalli", 
    "Annnihalli": "Angnihalli", "Annihlli": "Angnihalli", "Ajappanahalli": "Anjappanhalli",
    "Appenahalli": "Anjappanhalli", "Appannanahalli": "Anjappanhalli", "Alalaghatta": "Alalugatta",
    "Alambadijothinahalli": "Alambadijotinahalli", "Alambagiri": "Alamgiri",
    "Andrahalli": "Aarahalli", "Angondahalli": "Aarahalli", "Mindahalli": "Aarahalli",
    "Angadimallahalli": "Angadimallanahalli", "Annasagar": "Annasagara", "Ansagara": "Annasagara",
    "Anumanthanagara": "Hanumanthanagara", "Aonnegownepalli": "Sonegownapalli",
    "Apennahalli": "Appenahalli", "Gopenahalli": "Appenahalli", "Papenahalli": "Appenahalli",
    "A hosahalli": "Hosahalli", "A mothakapalli": "Mothakapalli", "Aarahalli": "Karahalli",
    "Ivarahalli": "Karahalli", "Iwarahalli": "Karahalli", "Aroghatta": "Haroghatta",
    "Asrihal": "Asrihalli", "Arehalli": "Asrihalli", "Avalakupp": "Avalakuppam",
    "Avalakuppa": "Avalakuppam", "Avalakuppm": "Avalakuppam", "Avalakuppma": "Avalakuppam",
    "Avulakuppam": "Avalakuppam", "Avula kuppam": "Avulakuppam", "Avulu kuppam": "Avulakuppam",
    "ayverhalli": "Kaverahalli",
    
    # B: Bommathanahalli cluster
    "Bomaganahalli": "Bommathanahalli", "Bommthahally": "Bommathanahalli", "Bommasandra": "Bommasandra",
    "Boochepalli": "Boochepalli", "Bochapalli": "Bochapalli", "Buchepalli": "Buchepalli",
    "B kothuru": "B. Kothuru", "N kothur": "B. Kothuru", "V. Kothur": "B. Kothuru", "Kothuru": "B. Kothuru",
    "B. Basavanahalli": "Badavanahalli", "Bachihalli": "Kachipalli", "Nachohalli": "Kachipalli",
    "Badamkanahalli": "Badavanahalli", "Bagavarahalli": "Badavanahalli", "Madanahalli": "Badavanahalli",
    "Bagepalli": "Bagepalli", "Balageri": "Balageri", "Balahalli": "Byalahalli",
    "Balenahalli": "Byalahalli", "Halahalli": "Byalahalli", "Malahalli": "Byalahalli",
    "Balakogilu": "Balakogilu", "Balandrapalli V": "Bandapalli", "Balekonna": "Balekonna",
    "Halenahalli": "Balenahalli", "Kalenahalli": "Balenahalli", "Kallenahalli": "Balenahalli",
    "Balla": "Balla", "Ballammanahalli": "Balahalli", "Bimmanahalli": "Bimmanahalli",
    "Kallanahalli": "Kallanahalli", "Ballapana hatti": "Ballappana hatti", "Banagiri": "Banagiri",
    "Banasandra": "Bansandra", "Kannasandra": "Bansandra", "Kansandra": "Bansandra",
    "Channasandra": "Bansandra", "Banavara": "Benavara", "Bennavara": "Benavara",
    "Bandarlahalli": "Bandarlahalli", "Bandralahalli": "Bandralahalli", "Bisanahalli": "Bisanahalli",
    "Bandarlapalli": "Bandarlapalli", "Bangaragere": "Bangaragere", "Bangarihatti": "Bangarihatti",
    "Bangavaadi": "Bangavadi", "Baramnakothuru": "Baramnakothuru", "Barshenahalli": "Barshenahalli",
    "Masthenahalli": "Masthenahalli", "Mastenahalli": "Mastenahalli", "dasenahalli": "Dasenahalli",
    "Battalahalli": "Battalahalli", "Batwarahalli": "Batwarahalli", "Byalahalli": "Byalahalli",
    "Batwara Halli": "BatwaraHalli", "Bavanath": "Bavanath", "Bayapanapalli": "Boyanapalli",
    "Nayanapalli": "Nayanapalli", "Byppanahalli": "Byppanahalli", "Bechaganahalli": "Bechaganahalli",
    "Belaganahalli": "Belaganahalli", "Beechagondahalli": "Beechagondahalli", "Benthganahalli": "Benthganahalli",
    "Beddali": "Reddalli", "Beeramanahalli": "Veeramanahalli", "Biramanahalli": "Biramanahalli",
    "Peramajanahalli": "Peramajanahalli", "Beerugundlapalli": "Berugundlapalli", "Berugudalapalli": "Berugudalapalli",
    "Beggli Benachenahalli": "Beggli Benachenahalli", "Bela Kokila": "Bala Kokila",
    "Benakanahalli": "Benakanahalli", "Biraganahalli": "Biraganahalli", "Belavadi": "Belavadi",
    "Bellambari": "Bellambari", "Bellara": "Bellara", "Bellaradahatti": "Bellaradahatti",
    "Benaganakuppam": "Benanakuppam", "Bendanakuppam": "Bendanakuppam", "Bendanalakuppa": "Bendanakuppam",
    "Bennagur": "Bennangur", "Bennvar": "Bennvar", "Benwara": "Benavara",
    "Boyanapalle": "Boyanapalli", "Boyanaplli": "Boyanapalli", "Bomanaplli": "Boyanapalli",
    "Bommathanahalli": "Bommathanahalli", "Boranakanive": "Boranakanive", "Budadimitte": "Budadimitte",
    "Budhikotte": "Budhikotte", "Budi betta": "Budi betta", "Buduguru": "Buduguru", "Bugaduru": "Bugaduru",
    "Bukkanahalli": "Bukkanahalli", "Nukkanahalli": "Nukkanahalli", "Busanahalli": "Busanahalli",
    "Buramakalahalli": "Buramakalahalli", "Burasidanapalli": "Burasidanapalli", "Hunasanahalli": "Hunasanahalli",
    "Byadanooru": "Byadanooru", "Byadanur": "Byadanur", "Bylamatta": "Bylamatta",
    "Bypalali": "Bypalali", "Byrapalli": "Byrapalli", "Byrapahalli": "Byrapahalli",
    "Byralinganahalli": "Byralinganahalli", "Byranayakanhalli": "Byranayakanhalli", "Byrasandra": "Byrasandra",
    "buchepalli": "Buchepalli", "bacchepel": None, "Bomsdra": "Bomsdra",
    
    # C: Chadmanahalli, Chinchadahalli clusters
    "CK pura": "CK pura", "Cr palya": "Cr palya", "Cettibala": "Cettibala", 
    "Chettibala": "Chettibala", "Chaanhalli": "Chaanhalli", "Chadhumanahalli": "Chadhumanahalli",
    "Chadmanahalli": "Chadmanahalli", "Chadmanhalli": "Chadmanhalli", "Chadunalli": "Chadunalli",
    "Chainpur": "Chainpur", "Chaldhiganahalli": "Chaldhiganahalli", "Chaldiganapalli": "Chaldiganapalli",
    "Chamarahalli": "Chamarahalli", "Chana Kashipur": "Chana Kashipur", "Chandrashekara pura": "Chandrashekarapura",
    "Channakeshavapura": "Channakeshavapura", "Channappanahalli": "Channappanahalli",
    "Channarayapura": "Channarayapura", "Channenahalli": "Channenahalli", "Chdumanahalli": "Chdumanahalli",
    "Chenarddypalli": "Chenarddypalli", "Chenguballa": "Chenguballa",
    "Chichdahalli": "Chichdahalli", "Chigarapura": "Chigarapura", "Chikattigenahalli": "Chikattigenahalli",
    "Chika Belavadi": "Chika Belavadi", "Chikka Belavadi": "Chikka Belavadi", "Chillapalli": "Chillapalli",
    "Chillapanahalli": "Chillapanahalli", "Chillappanahalli": "Chillappanahalli", "Chinappalli": "Chinappalli",
    "Chinapura": "Chinapura", "Chinchadahalli": "Chinchadahalli", "Chinchadlahalli": "Chinchadlahalli",
    "Chinchandahalli": "Chinchandahalli", "Chinchandlahalli": "Chinchandlahalli", "Chindalahalli": "Chindalahalli",
    "Chinthandapalli": "Chinthandapalli", "Chinthandpalli": "Chinthandpalli", "Chitnahalli": "Chitnahalli",
    "Chittaganahalli": "Chittaganahalli", "Cholagatta": "Cholagatta", "Chowdadenahalli": "Chowdadenahalli",
    "Chowdenahalli": "Chowdenahalli", "Chowdepalli": "Chowdepalli", "Ck Pura": "Ck Pura",
    
    # D: Doddahalli cluster
    "Dadikuppa": "Dadikuppam", "Dadikuppam": "Dadikuppam", "Dalakothur": "Dalakothur",
    "Dalasagere": "Dalasagere", "Dalasanur": "Dalasanur", "Dalasnur": "Dalasnur",
    "Dalavaihalli": "Dalavaihalli", "Dallavihosahalli": "Dallavihosahalli", "Dandagaanahalli": "Dandagaanahalli",
    "Dappaguntte": "Dappaguntte", "Dasaralpalli": "Dasaralpalli", "Dasarlhalli": "Dasarlhalli",
    "Dasimanipalli": "Dasimanipalli", "Dasthampalli": "Dasthampalli", "Dasudi": "Dasudi",
    "Davadabetta": "Davadabetta", "Devadabetta": "Devadabetta", "Devarabetta": "Devarabetta",
    "Devalapura": "Devalapura", "Devarabanda": "Devarabanda", "Devarahatti": "Devarahatti",
    "Devaramane palya": "Devaramane palya", "Devaraysamudra": "Devaraysamudra", "Dhalavahosahalli": "Dhalavahosahalli",
    "Dhantikuppam": "Dhantikuppam", "Dhastampalli": "Dhastampalli", "Dhodda bommanahalli": "Dhodda bommanahalli",
    "Dhoddakambali": "Dhoddakambali", "Dhulapalli": "Dhulapalli", "Diguvapalli": "Diguvapalli",
    "Dimbala": "Dimbala", "Dinnehosahalli": "Dinnehosahalli", "Dinnur": "Dinnur",
    "Doddaankanahalli": "Doddaankanahalli", "Doddabelavadi": "Doddabelavadi", "Doddagollarahatti": "Doddagollarahatti",
    "Doddahalli": "Doddahalli", "Doddaiyar villege": "Doddaiyar villege", "Doddaiyer": "Doddaiyer",
    "Doddakambali": "Doddakambali", "Doddakaramakalahalli": "Doddakaramakalahalli", "Doddakaramakkalahalli": "Doddakaramakkalahalli",
    "Doddakari": "Doddakari", "Doddanahalli village": "Doddanahalli village", "Doddanahatti": "Doddanahatti",
    "Doddanhalli": "Doddanhalli", "Doddavallabi": "Doddavallabi", "Doddayalasemadi": "Doddayalasemadi",
    "Doddayur": "Doddayur", "Doddenahaii": "Doddenahaii", "Doddewalagamadi": "Doddewalagamadi",
    "Doddkabali": "Doddkabali", "Doddkaballi": "Doddkaballi", "Doddnahalli": "Doddnahalli",
    "Dommathamari": "Dommathamari", "Doodagadalahalli": "Doodagadalahalli", "Dooddkabali": "Dooddkabali",
    "Dulapalli": "Dulapalli", "Dwarasandra": "Dwarasandra", "Dyavaiyanappalya": "Dyavaiyanappalya",
    "Dyavayyanapalya": "Dyavayyanapalya",
    
    # E-G: Various clusters
    "Emmekarike hatti": "Emmekarike hatti", "Emmekarikehatti": "Emmekarikehatti", "Erangampalli": "Erangampalli",
    "Erenahalli": "Erenahalli", "Gadadasanahalli": "Gadadasanahalli", "Gadde kannur": "Gaddekannuru",
    "Gaddekannuru": "Gaddekannuru", "Gaddekanoor": "Gaddekanoor", "Gadduru": "Gadduru", "Gaduru": "Gaduru",
    "Gaja kannur": "Gaja kannur", "Gajag": "Gajaga", "Gajaga": "Gajaga", "Gajulabavi": "Gajulabavi",
    "Gampalahalli": "Gampalahalli", "Gandhodalli": "Gandhodalli", "Gandla palli": "Gandla palli",
    "Gangapur": "Gangapur", "Gangapura": "Gangapura", "Gangasagara": "Gangasagara", "Ganjigunte": "Ganjigunte",
    "Ganjiguntte": "Ganjiguntte", "Ganlapalli": "Ganlapalli", "Gantenahalli": "Gantenahalli",
    "Garudapallya": "Garudapallya", "Gesthampalli": "Gesthampalli", "Gesthaplli": "Gesthaplli",
    "Giddegowdanahalli": "Giddegowdanahalli", "Ginnappanahatti": "Ginnappanahatti", "Giranahalli": "Giranahalli",
    "Giranali": "Giranali", "Giranalli": "Giranalli", "Girijampet": "Girijampet", "Girijanapete": "Girijanapete",
    "Goddanapalya": "Goddanapalya", "Godekere": "Godekere", "Gododmakanapalli": "Gododmakanapalli",
    "Goliganhalli": "Goliganhalli", "Gollaguruvenahalli": "Gollaguruvenahalli", "Gollahalli": "Gollahalli",
    "Gollanakante": "Gollanakante", "Gollanakunte": "Gollanakunte", "Gollapalli": "Gollapalli",
    "Gondipalya": "Gondipalya", "Gondivarahalli": "Gondivarahalli", "Gooliganahallu": "Gooliganahallu",
    "Gopal Devarahalli": "Gopal Devarahalli", "Goravanhalli": "Goravanhalli", "Gowdanahalli": "Gowdanahalli",
    "Gowdanakunte": "Gowdanakunte", "Gowdeti": "Gowdeti", "Gowravanahalli": "Gowravanahalli",
    "Gubalagutte": "Gubalagutte", "Gudarahalli": "Gudarahalli", "Gudigondahalli": "Gudigondahalli",
    "Gudigondanhalli": "Gudigondanhalli", "Gudipalle": "Gudipalle", "Gudipalli": "Gudipalli",
    "Gudlapura": "Gudlapura", "Gudumarlahalli": "Gudumarlahalli", "Gudur": "Gudur", "Gujjanadu": "Gujjanadu",
    "Gullakunte": "Gullakunte", "Gummareddypura": "Gummareddypura", "Gundesettipalli": "Gundesettipalli",
    "Gundeshettipalli": "Gundeshettipalli", "Gunnahalli": "Gunnahalli", "Gurugangiguriki": "Gurugangiguriki",
    "Gutluru": "Gutluru", "Guttahalli": "Guttahalli", "Guttalli": "Guttalli", "Guttshtepalli": "Guttshtepalli",
    "gopenhalli": "Gopenahalli",
    
    # H: Hanumanatha cluster
    "H golllahalli": "H golllahalli", "H nallapalli": "H nallapalli", "H.malandahalli": "H.malandahalli",
    "H.malandhalli": "H.malandhalli", "Habbini": "Habbini", "Hagadhalli": "Hagadhalli",
    "Hagodnahalli": "Hagodnahalli", "Hakkipikki colony": "Hakkipikki colony", "Hakkipikki kalvani": "Hakkipikki kalvani",
    "Handechikahalli": "Handechikahalli", "Handechikanahalli": "Handechikanahalli", "Handechikanalli": "Handechikanalli",
    "Handechikkanahalli": "Handechikkanahalli", "Hang": "Hang", "Hangla": "Hangla",
    "Hanumanabetta": "Hanumanabetta", "Hanumanahalli": "Hanumanahalli", "Hanumanathapally": "Hanumanathapally",
    "Hanumanbetta": "Hanumanbetta", "Hanumanthanagara": "Hanumanthanagara", "Hanumanthapura": "Hanumanthapura",
    "Hanumantpura": "Hanumantpura", "Hanumanupally": "Hanumanupally", "Hanumathanahalli": "Hanumathanahalli",
    "Haradagere": "Haradagere", "Haradhagere": "Haradhagere", "Haralakutte village": "Haralakutte village",
    "Haralukuntte": "Haralukuntte", "Harati": "Harati", "Hariharapura": "Hariharapura",
    "Hariharpura": "Hariharpura", "Harikunte": "Harikunte", "Harjenahalli": "Harjenahalli",
    "Harlikunte": "Harlikunte", "Harlikuntr": "Harlikuntr", "Harlikunts": "Harlikunts",
    "Harlkunte": "Harlkunte", "Haroghatta": "Haroghatta", "Harti": "Harti",
    "Hartimallandahalli": "Hartimallandahalli", "Hartimallandalli": "Hartimallandalli", "Hatna": "Hatna",
    "Hatti": "Hatti", "Havinalu": "Havinalu", "Havinamadugu": "Havinamadugu",
    "Herakarapanahalli": "Herakarapanahalli", "Hindiskere": "Hindiskere", "Hirekattigenahalli": "Hirekattigenahalli",
    "Hireyapalli": "Hireyapalli", "Hodalvadi": "Hodalvadi", "Hodhalawadi": "Hodhalawadi",
    "Hogalagere": "Hogalagere", "Holali village": "Holali village", "Holalihosur": "Holalihosur",
    "Holalli": "Holalli", "Hollamballi": "Hollamballi", "Honganahalli": "Honganahalli",
    "Honganapalli": "Honganapalli", "Hoovahalli": "Hoovahalli", "Hosabadavane": "Hosabadavane",
    "Hosaburju": "Hosaburju", "Hosaburuju": "Hosaburuju", "Hosadurg": "Hosadurg",
    "Hosadurga": "Hosadurga", "Hosagollarahatti": "Hosagollarahatti", "Hosagollarahatty": "Hosagollarahatty",
    "Hosahali": "Hosahali", "Hosahalli": "Hosahalli", "Hosahalli Palya": "Hosahalli Palya",
    "Hosamallanahaalli": "Hosamallanahaalli", "Hosamallanahalli": "Hosamallanahalli", "Hosamane a": "Hosamane a",
    "Hosapalli": "Hosapalli", "Hothuru village": "Hothuru village", "Huarasanahalli": "Huarasanahalli",
    "Hudukula": "Hudukula", "Hulibele": "Hulibele", "Hulkur": "Hulkur", "Hulkuru": "Hulkuru",
    "Hullanakallu": "Hullanakallu", "Hunasanahalli": "Hunasanahalli", "Hunasemaradahalli": "Hunasemaradahalli",
    "Hunukuladoddi": "Hunukuladoddi", "Huralahalli": "Huralahalli", "Hutoor": "Hutoor",
    "Hutthuru": "Hutthuru", "Hutturu": "Hutturu", "Huvvinhalli": "Huvvinhalli",
    "Hytharasanahalli": "Hytharasanahalli",
    
    # I: Iavarahalli cluster
    "Ianarahosahalli": "Ianarahosahalli", "Ianorahosahalli": "Ianorahosahalli", "Iavarahalli": "Iavarahalli",
    "Imarakunta": "Imarakunta", "Indhiranagar": "Indhiranagar", "Iragampalli": "Iragampalli",
    "Iragasandra": "Iragasandra", "Itharasanahalli": "Itharasanahalli", "Itkaralapalli": "Itkaralapalli",
    "Ittukuralapalli": "Ittukuralapalli", "Iyappalli": "Iyappalli", "Iynorahoshalli": "Iynorahoshalli",
    "Iytarasanahalli": "Iytarasanahalli",
    
    # J-K: Various
    "J. Palya": "J. Palya", "J.I.Dalawai Hosahalli": "J.I.Dalawai Hosahalli", "J.I.Karadaguru": "J.I.Karadaguru",
    "J.I.Kogilahalli": "J.I.Kogilahalli", "J.I.Madenahalli": "J.I.Madenahalli", "J.I.Mallapalli": "J.I.Mallapalli",
    "Jaladenahalli": "Jaladenahalli", "Jambapura": "Jambapura", "Janapanahalli": "Janapanahalli",
    "Janappalli": "Janappalli", "Jangam gurjayanhalli": "Jangam gurjayanhalli", "Jangamagurjenahallu": "Jangamagurjenahallu",
    "Jangamahosahalli": "Jangamahosahalli", "Jangamapura": "Jangamapura", "Jaurayanahalli": "Jaurayanahalli",
    "Jeedigutlametta": "Jeedigutlametta", "Jounipalle": "Jounipalle", "Junjanahslli": "Junjanahslli",
    "Junjinahali": "Junjinahali", "K Gollahalli": "K Gollahalli", "K gollahalli": "K gollahalli",
    "K ragutahalli": "K ragutahalli", "Kaamagondanahalli": "Kaamagondanahalli", "Kabatthanahalli": "Kabatthanahalli",
    "Kachipalli": "Kachipalli", "Kadadhavandlahalli": "Kadadhavandlahalli", "Kadagatturu": "Kadagatturu",
    "Kadagur": "Kadagur", "Kadaguru": "Kadaguru", "Kadagutturu": "Kadagutturu", "Kadahalli": "Kadahalli",
    "Kadakur": "Kadakur", "Kadakuru": "Kadakuru", "Kadapalakere": "Kadapalakere", "Kadariganikippa": "Kadariganikippa",
    "Kadaripura": "Kadaripura", "Kadgur": "Kadgur", "Kadhirenahalli": "Kadhirenahalli", "Kadhiripura": "Kadhiripura",
    "Kadhirupura": "Kadhirupura", "Kadiredevanakotte": "Kadiredevanakotte", "Kadirenahalli": "Kadirenahalli",
    "Kadudevandlahalli": "Kadudevandlahalli", "Kadur": "Kadur", "Kagathi": "Kagathi",
    "Kaidala": "Kaidala", "Kaiwara": "Kaiwara", "Kakarlavanka": "Kakarlavanka", "Kalahastipura": "Kalahastipura",
    "Kalahosahalli": "Kalahosahalli", "Kalanahalli": "Kalanahalli", "Kalavasahalli": "Kalavasahalli",
    "Kallambella": "Kallambella", "Kallikuppa": "Kallikuppa", "Kallipura": "Kallipura", "Kallur": "Kallur",
    "Kalluru": "Kalluru", "KaluKurupalli": "KaluKurupalli", "Kamadenahalli": "Kamadenahalli",
    "Kamagondanahalli": "Kamagondanahalli", "Kamanadurga": "Kamanadurga", "Kamandahalli": "Kamandahalli",
    "Kamasadra": "Kamasadra", "Kambadahalli": "Kambadahalli", "Kamdanalli": "Kamdanalli",
    "Kammasandra": "Kammasandra", "Kamthampalli": "Kamthampalli", "Kanagadahalli": "Kanagadahalli",
    "Kangadahalli": "Kangadahalli", "Kangalahalli": "Kangalahalli", "Kangandlahalli": "Kangandlahalli",
    "Kangdlahalli": "Kangdlahalli", "Kanive Kallu": "Kanive Kallu", "Kanivekallu": "Kanivekallu",
    "Kannameddi": "Kannameddi", "Kannru": "Kannru", "Kannur": "Kannur", "Kannuru": "Kannuru",
    "Kantenahalli": "Kantenahalli", "Kappalli": "Kappalli", "Kappenahalli": "Kappenahalli",
    "Karadaganahalli": "Karadaganahalli", "Karadagur": "Karadagur", "Karadaguru": "Karadaguru",
    "Karadgur": "Karadgur", "Karadi": "Karadi", "Karaduguru": "Karaduguru", "Karahalli": "Karahalli",
    "Karakanahatti": "Karakanahatti", "Karamannahslli": "Karamannahslli", "Kardaguru": "Kardaguru",
    "Kardiganahalli": "Kardiganahalli", "Kardugur": "Kardugur", "Karejavanahalli": "Karejavanahalli",
    "Karigadanahalli": "Karigadanahalli", "Karuduguru": "Karuduguru", "Kasaba": "Kasaba",
    "Kasapura": "Kasapura", "Kasettipalli": "Kasettipalli", "Kashettippalli": "Kashettippalli",
    "Kashipura": "Kashipura", "Katagondanahalli": "Katagondanahalli", "Katamdevartti": "Katamdevartti",
    "Katarala muddalahalli": "Katarala muddalahalli", "Katharakallu": "Katharakallu", "Kathrikehal": "Kathrikehal",
    "Kathrikehalu": "Kathrikehalu", "Katrikehal": "Katrikehal", "Katrikehalli": "Katrikehalli",
    "Kattampalli": "Kattampalli", "Kattaveeranahalli": "Kattaveeranahalli", "Kattaveranahalli": "Kattaveranahalli",
    "Kattemadevara Hatti": "Kattemadevara Hatti", "Kavanadala": "Kavanadala", "Kavaragaanahalli": "Kavaragaanahalli",
    "Kavaraganahalli": "Kavaraganahalli", "Kavarganahalli": "Kavarganahalli", "Kaveneenahalli": "Kaveneenahalli",
    "Kaverahalli": "Kaverahalli", "Kedhirenahalli": "Kedhirenahalli", "Keerthi kuppa": "Keerthi kuppa",
    "Kembodi": "Kembodi", "Kemparayanahatti": "Kemparayanahatti", "Kemppapura": "Kemppapura",
    "Kenamakanapalli": "Kenamakanapalli", "Kenamakanaplli": "Kenamakanaplli", "Kendanahalli": "Kendanahalli",
    "Kendenahalli": "Kendenahalli", "Kenemakalapalli": "Kenemakalapalli", "Kenemakanapalli": "Kenemakanapalli",
    "Kenkere": "Kenkere", "Kesaranahalli": "Kesaranahalli", "Kesaranahallu": "Kesaranahallu",
    "Kethaganahalli": "Kethaganahalli", "Kethaganhalli": "Kethaganhalli", "Kharghar": "Kharghar",
    "Kilarlahalli": "Kilarlahalli", "Kilkuppa": "Kilkuppa", "Killadahalli": "Killadahalli",
    "Killkambali": "Killkambali", "Kiluvaholi": "Kiluvaholi", "Kithandir": "Kithandir",
    "Kittaganahalli": "Kittaganahalli", "Koamadagu": "Koamadagu", "Kodagu": "Kodagu",
    "Kodenahalli": "Kodenahalli", "Kodigenahalli": "Kodigenahalli", "Kodihalli": "Kodihalli",
    "Kodikannuru": "Kodikannuru", "Kodikannut": "Kodikannut", "Kodugurki": "Kodugurki",
    "Koganapalli": "Koganapalli", "Kogarahali": "Kogarahali", "Kogarahalli": "Kogarahalli",
    "Kogatam": "Kogatam", "Kogilahalli": "Kogilahalli", "Kogile": "Kogile", "KolaGanja Nalli": "KolaGanja Nalli",
    "Koladevara hatti": "Koladevara hatti", "Koladevarahatti": "Koladevarahatti", "Kolaganjenahalli": "Kolaganjenahalli",
    "Kolapalli": "Kolapalli", "Kollur": "Kollur", "Kollura": "Kollura", "Kolluru": "Kolluru",
    "Konakurike": "Konakurike", "Konanakurike": "Konanakurike", "Konapalli": "Konapalli",
    "Kondapura": "Kondapura", "Kondarajanahalli": "Kondarajanahalli", "Kondenahalli": "Kondenahalli",
    "Kondhalli": "Kondhalli", "Kondrajanalli": "Kondrajanalli", "Konerukuppam": "Konerukuppam",
    "Konganahalli": "Konganahalli", "Konganalli": "Konganalli", "Kongatam": "Kongatam",
    "Kongsrahalli": "Kongsrahalli", "Koonahalli": "Koonahalli", "Kootharajanahalli": "Kootharajanahalli",
    "Kopahalli": "Kopahalli", "Koragere": "Koragere", "Korati": "Korati", "Korevenuru": "Korevenuru",
    "Kota gudda": "Kota gudda", "Kotabade": "Kotabade", "Kotaguadda": "Kotaguadda", "Kotagudda": "Kotagudda",
    "Kotekallur": "Kotekallur", "Koteri": "Koteri", "Kothamagala": "Kothamagala", "Kothmangala": "Kothmangala",
    "Kothur": "Kothur", "Kothutu": "Kothutu", "Kotiganahallai": "Kotiganahallai", "Kotiganahalli": "Kotiganahalli",
    "Kotiganhalli": "Kotiganhalli", "Kottekrishnahalli": "Kottekrishnahalli", "Krishnagiri": "Krishnagiri",
    "Krishnapura": "Krishnapura", "Krishnapuram": "Krishnapuram", "Krishnasagara": "Krishnasagara",
    "Krishnavaram": "Krishnavaram", "Kuditavarehalli": "Kuditavarehalli", "Kukurubur": "Kukurubur",
    "Kulooru": "Kulooru", "Kulur": "Kulur", "Kuluru": "Kuluru", "Kumbarahalli": "Kumbarahalli",
    "Kumbarhalli": "Kumbarhalli", "Kumgunte": "Kumgunte", "Kunigalthimmanapalya": "Kunigalthimmanapalya",
    "Kunikanhalli": "Kunikanhalli", "Kuntramanalli": "Kuntramanalli", "Kuppalli": "Kuppalli",
    "Kuppam palli": "Kuppam palli", "Kuppampalya": "Kuppampalya", "Kuppanalli": "Kuppanalli",
    "Kuragall": "Kuragall", "Kurbur": "Kurbur", "Kurki": "Kurki", "Kurubanahalli": "Kurubanahalli",
    "Kurubarahalli": "Kurubarahalli", "Kurubur": "Kurubur", "Kuruburu": "Kuruburu", "Kurugal": "Kurugal",
    "Kururu": "Kururu", "Kutandahalli": "Kutandahalli", "Kuthadahalli": "Kuthadahalli",
    "Kuthandahalli": "Kuthandahalli", "Kutharajanahalli": "Kutharajanahalli", "Kuthoganapsalli": "Kuthoganapsalli",
    "Kyasambally": "Kyasambally", "Kyathaganahalli": "Kyathaganahalli", "kannur": "Kannur",
    "krishnapuram": "Krishnapuram", "karudukur": "Karudukur", "gonamakanapalli": "Gonamakanapalli",
    "guliganahalli": "Guliganahalli",
    
    # L-M: Large cluster
    "Lakkanahalli": "Lakkanahalli", "Lakkenahalli": "Lakkenahalli", "Laklihatti": "Laklihatti",
    "Lakmagondanahalli": "Lakmagondanahalli", "Lakmakondanahalli": "Lakmakondanahalli",
    "Lakshamanpura": "Lakshamanpura", "Lakshimi sagara": "Lakshimi sagara", "Lakshmi Sagara": "Lakshmi Sagara",
    "Lakshmi sagara": "Lakshmi sagara", "Lakshmisagara": "Lakshmisagara", "M k puram": "M k puram",
    "M.n sagara": "M.n sagara", "Maadhugujenalli": "Maadhugujenalli", "Maarpalli": "Maarpalli",
    "Madala": "Madala", "Madalapura": "Madalapura", "Madanamadu": "Madanamadu", "Madapura": "Madapura",
    "Madara red lhalli": "Madara red lhalli", "Madderi": "Madderi", "Madheri": "Madheri",
    "Madhmangla": "Madhmangla", "Madiva": "Madiva", "Madival": "Madival", "Madivala": "Madivala",
    "Madivala m": "Madivala m", "Madivala majara kothur": "Madivala majara kothur", "Madlerahalli": "Madlerahalli",
    "Madura redally": "Madura redally", "Maduvathi": "Maduvathi", "Mageri": "Mageri",
    "Magundi": "Magundi", "Mahadevapura": "Mahadevapura", "Mailandahalli": "Mailandahalli",
    "Majar guttahalli": "Majar guttahalli", "Majar guttahli": "Majar guttahli", "Majara Guttahali": "Majara Guttahali",
    "Majra reddlerly": "Majra reddlerly", "Makarahalli": "Makarahalli", "Makulapalli": "Makulapalli",
    "Malandalli": "Malandalli", "Malapanahalli": "Malapanahalli", "Malashetanahally": "Malashetanahally",
    "Malashettanahally": "Malashettanahally", "Maligani": "Maligani", "Malimorerapalli": "Malimorerapalli",
    "Mallahalli": "Mallahalli", "Mallanayakanahalli": "Mallanayakanahalli", "Mallashetanahally": "Mallashetanahally",
    "Mallashettanahalli": "Mallashettanahalli", "Mallashettihalli": "Mallashettihalli",
    "Mallashettihally": "Mallashettihally", "Mallikapura": "Mallikapura", "Mallipattana": "Mallipattana",
    "Manchandahalli": "Manchandahalli", "Manchigaanahalli": "Manchigaanahalli", "Manchiganahalli": "Manchiganahalli",
    "Manege": "Manege", "Manneyanapalli": "Manneyanapalli", "Maradasanahalli": "Maradasanahalli",
    "Maradhagatta": "Maradhagatta", "Marallahalli": "Marallahalli", "Maranadu": "Maranadu",
    "Marandahalli": "Marandahalli", "Marapalli": "Marapalli", "Marenadu": "Marenadu",
    "Maridasanahally": "Maridasanahally", "Mariyappanahalli": "Mariyappanahalli", "Marjenahalli": "Marjenahalli",
    "Markandapura": "Markandapura", "Markandeyapura": "Markandeyapura", "Markondapura": "Markondapura",
    "Marpalli": "Marpalli", "Marsandalli": "Marsandalli", "Mastanahalli": "Mastanahalli",
    "Mastenahalli": "Mastenahalli", "Masthenahalli": "Masthenahalli", "Mathikere": "Mathikere",
    "Matnahalli": "Matnahalli", "Mavahalli": "Mavahalli", "Mavalli": "Mavalli",
    "Mavina Halli Hatti": "Mavina Halli Hatti", "Mayladahalli": "Mayladahalli", "Medigeshi": "Medigeshi",
    "Medihala": "Medihala", "Medithambihalli": "Medithambihalli", "Meesaganahalli": "Meesaganahalli",
    "Meesganahalli": "Meesganahalli", "Meetakothur": "Meetakothur", "Melaiganhalli": "Melaiganhalli",
    "Melpalli": "Melpalli", "Minda Halli": "Minda Halli", "MindaHalli": "MindaHalli",
    "Mindigal": "Mindigal", "Minjenahalli": "Minjenahalli", "Mittakallahalli": "Mittakallahalli",
    "Mittakunte": "Mittakunte", "Mkpuram": "Mkpuram", "Mohamad pura": "Mohamad pura",
    "Mohamad puram": "Mohamad puram", "Moodravu": "Moodravu", "Moparahalli": "Moparahalli",
    "Morasallapalli": "Morasallapalli", "Motakothuru": "Motakothuru", "Mothakaoalli": "Mothakaoalli",
    "Mothakapalli": "Mothakapalli", "Mothapill": "Mothapill", "Mottakothuru": "Mottakothuru",
    "Msdivala": "Msdivala", "Mshadevapura": "Mshadevapura", "Mudanayakanahalli": "Mudanayakanahalli",
    "Muddappanapalya": "Muddappanapalya", "Muddenapalle": "Muddenapalle", "Muddnaalli": "Muddnaalli",
    "Muddnapalli": "Muddnapalli", "Mudenayakanhalli": "Mudenayakanhalli", "Mudhuvadi hosahalli": "Mudhuvadi hosahalli",
    "Mudimadu": "Mudimadu", "Mudugalahalli": "Mudugalahalli", "Mudugulli": "Mudugulli",
    "Muduvadi": "Muduvadi", "Muduvathi": "Muduvathi", "Mugadalabetta": "Mugadalabetta",
    "Mugahalli": "Mugahalli", "Mugalbele": "Mugalbele", "Mugnahalli": "Mugnahalli",
    "Mugubele": "Mugubele", "Mullahalli": "Mullahalli", "Mummadesagara": "Mummadesagara",
    "Murandahalli": "Murandahalli", "Mushtoor": "Mushtoor", "Mustoor": "Mustoor",
    "Muthugadahalli": "Muthugadahalli", "Muthugadalli": "Muthugadalli", "Muthupalli": "Muthupalli",
    "Mutkulur": "Mutkulur", "Muttluru": "Muttluru", "Muttugadahalli": "Muttugadahalli",
    "Mylakabbe": "Mylakabbe", "Myle kallatti": "Myle kallatti", "madhmangla": "Madhmangla",
    "mageri": "Mageri",
    
    # N: Large cluster starting with N
    "NG Hulkur": "NG Hulkur", "Naaganaala": "Naaganaala", "Naayanhalli": "Naayanhalli",
    "Nadpali": "Nadpali", "Nadpalli": "Nadpalli", "Nagakoppa": "Nagakoppa", "Nagakuppa": "Nagakuppa",
    "Nagakuppam": "Nagakuppam", "Nagalamadike": "Nagalamadike", "Naganaala": "Naganaala",
    "Naganahalli": "Naganahalli", "Naganala": "Naganala", "Naganayakanahalli": "Naganayakanahalli",
    "Nagarahalli": "Nagarahalli", "Nagenahalli": "Nagenahalli", "Nagidhipalli": "Nagidhipalli",
    "Nakkanahalli": "Nakkanahalli", "Nakkanapalli": "Nakkanapalli", "Nalaganahalli": "Nalaganahalli",
    "Nalaganahally": "Nalaganahally", "Nalagutturu": "Nalagutturu", "Nallagatturu": "Nallagatturu",
    "Nallaguttalahalli": "Nallaguttalahalli", "Nallaguttur": "Nallaguttur", "Nallapalli": "Nallapalli",
    "Nallappalli": "Nallappalli", "Nalluru": "Nalluru", "Nambihalli": "Nambihalli",
    "Nanayanahlli": "Nanayanahlli", "Nandiganahalli": "Nandiganahalli", "Nandihalli": "Nandihalli",
    "Nanjanagadda": "Nanjanagadda", "Naranahalli": "Naranahalli", "Narasapura": "Narasapura",
    "Narayanahalli": "Narayanahalli", "Naryanahalli": "Naryanahalli", "Navane Boranahalli": "Navane Boranahalli",
    "Navave Boranahalli": "Navave Boranahalli", "Nayakarahalli": "Nayakarahalli", "Nayanahalli": "Nayanahalli",
    "Nayandharalli": "Nayandharalli", "Neelahalli": "Neelahalli", "Nenamanahalli": "Nenamanahalli",
    "Nenamanahallu": "Nenamanahallu", "Neralakere": "Neralakere", "Nernahalli": "Nernahalli",
    "Nernakallu": "Nernakallu", "Nernalli": "Nernalli", "Nernhalli": "Nernhalli",
    "Nernukallu": "Nernukallu", "Nidugurki": "Nidugurki", "Nilamanahalli": "Nilamanahalli",
    "Nilatur": "Nilatur", "Nillamanahally": "Nillamanahally", "Niltor": "Niltor",
    "Niltur": "Niltur", "Nimanapalli": "Nimanapalli", "Nirgundipalya": "Nirgundipalya",
    "No": None, "Nolenooru": "Nolenooru", "Nukkanaalli": "Nukkanaalli", "Nukkanahalli": "Nukkanahalli",
    "Nukkanhalli": "Nukkanhalli", "Nulenoor": "Nulenoor", "Nulenuru": "Nulenuru",
    "nakkanaHalli": "Nakkanahalli",
    
    # O-P: Various
    "Oabalapura": "Oabalapura", "Obepalli": "Obepalli", "Oltur": "Oltur",
    "Ombathuguli": "Ombathuguli", "Ombatthuguli": "Ombatthuguli", "Oolavadi": "Oolavadi",
    "Padadhampalli": "Padadhampalli", "Paladahalli": "Paladahalli", "Palavalli": "Palavalli",
    "Panasachowdanahalli": "Panasachowdanahalli", "Panasamakanahalli": "Panasamakanahalli",
    "Papanakona": "Papanakona", "Paravasahalli": "Paravasahalli", "Parehosahalli": "Parehosahalli",
    "Paresepalli": "Paresepalli", "Parshepalli": "Parshepalli", "Pathabalappalli": "Pathabalappalli",
    "Pavagada": "Pavagada", "Pavagada ruala": "Pavagada ruala", "Peadmpall": "Peadmpall",
    "Pedabomanapalli": "Pedabomanapalli", "Pedabomanaplli": "Pedabomanaplli", "Pedampalli": "Pedampalli",
    "Peddamplli": "Peddamplli", "Peddapalli": "Peddapalli", "Peduru": "Peduru",
    "Peelavaram": "Peelavaram", "Peeruru": "Peeruru", "Pegalapalli": "Pegalapalli",
    "Peramachanahalli": "Peramachanahalli", "Peramachanhalli": "Peramachanhalli", "Perjenahalli": "Perjenahalli",
    "Pilagondahalli": "Pilagondahalli", "Pilavaram": "Pilavaram", "Pillagotahalli": "Pillagotahalli",
    "Pillagundalli": "Pillagundalli", "Pillaguttahalli": "Pillaguttahalli", "Pillobaraddyhalli": "Pillobaraddyhalli",
    "Pilugundahalli": "Pilugundahalli", "Pilugundlahalli": "Pilugundlahalli", "Pitikatte": "Pitikatte",
    "Pittenahalli": "Pittenahalli", "Polanayakanahalli": "Polanayakanahalli", "Ponthaganahalli": "Ponthaganahalli",
    "Ponthakanahalli": "Ponthakanahalli", "Pooganahalli": "Pooganahalli", "Poogenahalli": "Poogenahalli",
    "Poovandahalli": "Poovandahalli", "Pothaganahalli": "Pothaganahalli", "Povandahalli": "Povandahalli",
    "Puchenahalli": "Puchenahalli", "Puganahalli": "Puganahalli", "Puli obaraddy halli": "Puli obaraddy halli",
    "Puliobakaraddahalli": "Puliobakaraddahalli", "Pulipreddyhslli": "Pulipreddyhslli", "Pura": "Pura",
    "Purahalli": "Purahalli", "Purnapalli": "Purnapalli", "Puttenahalli": "Puttenahalli",
    
    # R: Various
    "R Gollahalli": "R Gollahalli", "R. Gollarahatti": "R. Gollarahatti", "RD Roopa": "RD Roopa",
    "RD roopa": "RD roopa", "Rd roopa": "Rd roopa", "Rachapura": "Rachapura", "Raghupathi Hosahalli": "Raghupathi Hosahalli",
    "Ragunathapur": "Ragunathapur", "Ragunathapura": "Ragunathapura", "Raissandra": "Raissandra",
    "Raja pet rod": "Raja pet rod", "Rajakallalli": "Rajakallalli", "Rajathadripura": "Rajathadripura",
    "Rajpet": "Rajpet", "Rajpet Rood": "Rajpet Rood", "Ramakuppam": "Ramakuppam",
    "Ramanagara": "Ramanagara", "Ramanahalli": "Ramanahalli", "Ramapura": "Ramapura",
    "Ramapuram": "Ramapuram", "Ramarayanakote": "Ramarayanakote", "Ramasagara": "Ramasagara",
    "Ramasandra": "Ramasandra", "Ramayanakote": "Ramayanakote", "Ramkupam": "Ramkupam",
    "Ramsagar": "Ramsagar", "Ramsagara": "Ramsagara", "Ranganahalli": "Ranganahalli",
    "Ranganahlli": "Ranganahlli", "Rangapura": "Rangapura", "Rangapura G": "Rangapura G",
    "Rangapuradahatti": "Rangapuradahatti", "Rayalpad": "Rayalpad", "Rayasandra": "Rayasandra",
    "Reddahalli": "Reddahalli", "Reddalaplli": "Reddalaplli", "Reddalli": "Reddalli",
    "Reddihalli": "Reddihalli", "Reddyhalli": "Reddyhalli", "Rk puram": "Rk puram",
    "Rojoranahalli": "Rojoranahalli", "Rojornahalli": "Rojornahalli", "Ronur": "Ronur",
    "Rooppa": "Rooppa", "raysandara": "Rayasandra", "raysandara ": "Rayasandra",
    
    # S: Large cluster
    "S chadhumanalli": "S chadhumanalli", "S gollaplli": "S gollaplli", "Sadarahalli": "Sadarahalli",
    "Saganahalli": "Saganahalli", "Saganalli": "Saganalli", "Sagasandra": "Sagasandra",
    "Sakanahalli": "Sakanahalli", "Sakannahalli": "Sakannahalli", "Salkatte": "Salkatte",
    "Sambapura": "Sambapura", "Sanaganahalli": "Sanaganahalli", "Sanashpalli": "Sanashpalli",
    "Sandarhalli": "Sandarhalli", "Sangadahalli": "Sangadahalli", "Sanganahalli": "Sanganahalli",
    "Sanniyasipalli": "Sanniyasipalli", "Santhampalle": "Santhampalle", "Sarva Reddy Halli": "Sarva Reddy Halli",
    "Sarva Reddy halli": "Sarva Reddy halli", "Sarvareddyhalli": "Sarvareddyhalli", "Sarvatapur": "Sarvatapur",
    "Sasalu": "Sasalu", "Sathigenahalli": "Sathigenahalli", "Sattigenahalli": "Sattigenahalli",
    "Saynaboganahalli": "Saynaboganahalli", "Seasandra": "Seasandra", "Seebi": "Seebi",
    "Seebi agrahara": "Seebi agrahara", "Seebinayanapalya": "Seebinayanapalya", "Seegenahalli": "Seegenahalli",
    "Seekallu": "Seekallu", "Seesandra": "Seesandra", "Seethampalli": "Seethampalli",
    "Segnahalli": "Segnahalli", "Sekal": "Sekal", "Sekallu": "Sekallu", "Servareddahalli": "Servareddahalli",
    "Sesandra": "Sesandra", "Setepilli": "Setepilli", "Seteplli": "Seteplli", "Settiballa": "Settiballa",
    "Settipalli": "Settipalli", "Settpalli": "Settpalli", "Shanaboganahalli": "Shanaboganahalli",
    "Shantipuram": "Shantipuram", "Shanuboganahalli": "Shanuboganahalli", "Shatgunte": "Shatgunte",
    "Shathipurm": "Shathipurm", "Shattiganahalli": "Shattiganahalli", "Shattimadamangala": "Shattimadamangala",
    "Shavarahalli": "Shavarahalli", "Shedanakatte": "Shedanakatte", "Sheshadripuram": "Sheshadripuram",
    "Shettihalli": "Shettihalli", "Shettimadhamagala": "Shettimadhamagala", "Shettimadhamangala": "Shettimadhamangala",
    "Shettivarapalli": "Shettivarapalli", "Shetty Madhav Mangla": "Shetty Madhav Mangla",
    "Shetty madhala  Mangala": "Shetty madhala  Mangala", "Shetty madhamangala": "Shetty madhamangala",
    "Shettyhalli": "Shettyhalli", "Shillagere": "Shillagere", "Shillgri": "Shillgri",
    "Shilligeri": "Shilligeri", "Shilligri": "Shilligri", "Shingadhahalli": "Shingadhahalli",
    "Shingathalli": "Shingathalli", "Shisadri": "Shisadri", "Shpoor": "Shpoor",
    "Shreepura": "Shreepura", "Shylapura": "Shylapura", "Siddanahalli": "Siddanahalli",
    "Siddlekona": "Siddlekona", "Siddovor": "Siddovor", "Sidlekona": "Sidlekona",
    "Siduru": "Siduru", "Singadahalli": "Singadahalli", "Singondahalli": "Singondahalli",
    "Singondanahalli": "Singondanahalli", "Sivanikuppam": "Sivanikuppam", "Sogadabala": "Sogadabala",
    "Sogadaballa": "Sogadaballa", "Sogadapalla": "Sogadapalla", "Soggad Bhalla": "Soggad Bhalla",
    "Somakalahalli": "Somakalahalli", "Somalapura": "Somalapura", "Somanahalli": "Somanahalli",
    "Somaraaum palli": "Somaraaum palli", "Somarasanahalli": "Somarasanahalli", "Somarsanahalli": "Somarsanahalli",
    "Somarshanahalli": "Somarshanahalli", "Somarshanahalli y": "Somarshanahalli y", "Somarsmpalli": "Somarsmpalli",
    "Somasnadra": "Somasnadra", "Somayajalahalli": "Somayajalahalli", "Somenahalli village": "Somenahalli village",
    "Sonaihalli": "Sonaihalli", "Sondenahalli": "Sondenahalli", "Sondenahalli gollarahatti": "Sondenahalli gollarahatti",
    "Sonegownapalli": "Sonegownapalli", "Sonepali": "Sonepali", "Sonepalli": "Sonepalli",
    "Sonepallu": "Sonepallu", "Songon": "Songon", "Sonneganapalli": "Sonneganapalli",
    "Soolanayakanahally": "Soolanayakanahally", "Srinivasadra": "Srinivasadra", "Srinivasandra": "Srinivasandra",
    "Srinivasapur": "Srinivasapur", "Srinivasapura": "Srinivasapura", "Srinivaspuram": "Srinivaspuram",
    "Srisadhar": "Srisadhar", "Srisadhara": "Srisadhara", "Srishadhara": "Srishadhara",
    "Srivasadra": "Srivasadra", "Sthulasinayanapalli": "Sthulasinayanapalli", "Sugadaballa": "Sugadaballa",
    "Sugatur": "Sugatur", "Sugaturu": "Sugaturu", "Sugutur": "Sugutur", "Sugutur village": "Sugutur village",
    "Suguturu": "Suguturu", "Suladenahallu": "Suladenahallu", "Sulasetepalli": "Sulasetepalli",
    "Sulikunte": "Sulikunte", "Sundarapalya": "Sundarapalya", "Sundharapaly": "Sundharapaly",
    "Sunnanguru": "Sunnanguru", "Suryanaik tandya": "Suryanaik tandya", "Suvarnahalli": "Suvarnahalli",
    "Syanabogahali": "Syanabogahali", "sarvareddyhalli": "Sarvareddyhalli",
    
    # T-V: Various
    "T bandapalli": "T bandapalli", "T hosuru": "T hosuru", "T.N. Betta": "T.N. Betta",
    "TN Betta": "TN Betta", "TN betta": "TN betta", "Tadigol": "Tadigol", "Tailur cross": "Tailur cross",
    "Tambali": "Tambali", "Tata halli": "Tata halli", "Tatanagunte": "Tatanagunte",
    "Tatanguntte": "Tatanguntte", "Tatenahalli": "Tatenahalli", "Tatenahlli": "Tatenahlli",
    "Tatepalli": "Tatepalli", "Tatireddipalli": "Tatireddipalli", "Ternahalli": "Ternahalli",
    "Thadi": "Thadi", "Thallapalli": "Thallapalli", "Thamballi": "Thamballi", "Thambihalli": "Thambihalli",
    "Thammablli": "Thammablli", "Thammenahalli": "Thammenahalli", "Tharur": "Tharur",
    "Tharuru": "Tharuru", "Thathenahali": "Thathenahali", "Thaylur karsu": "Thaylur karsu",
    "Thernnahalli": "Thernnahalli", "Thimalapura": "Thimalapura", "Thimanahalli": "Thimanahalli",
    "Thimapura": "Thimapura", "Thimlapura": "Thimlapura", "Thimmalapura": "Thimmalapura",
    "Thimmanahalli": "Thimmanahalli", "Thimmannanayakanabetta": "Thimmannanayakanabetta",
    "Thimmapana": "Thimmapana", "Thimmapana hatti": "Thimmapana hatti", "Thimmapara": "Thimmapara",
    "Thimmappanahatti": "Thimmappanahatti", "Thimmappanahatto": "Thimmappanahatto", "Thimmapura": "Thimmapura",
    "Thimmasandra": "Thimmasandra", "Thipanahalli": "Thipanahalli", "Thipasa dra": "Thipasa dra",
    "Thippanadurga": "Thippanadurga", "Thippanahalli": "Thippanahalli", "Thippasandra": "Thippasandra",
    "Thippenahalli": "Thippenahalli", "Thippiahanadurga": "Thippiahanadurga", "Thiradevandahalli": "Thiradevandahalli",
    "Thirthapura": "Thirthapura", "Thodadhonahalli": "Thodadhonahalli", "Thokalaghatta": "Thokalaghatta",
    "Thongalakupp": "Thongalakupp", "Thoradevandahalli": "Thoradevandahalli", "Thoravedandahalli": "Thoravedandahalli",
    "Thoremane": "Thoremane", "Thotle": "Thotle", "Thotli": "Thotli", "Thtepalli": "Thtepalli",
    "Thulssinayanapalli": "Thulssinayanapalli", "Thumatagere": "Thumatagere", "Thumatagiri": "Thumatagiri",
    "Thumshi": "Thumshi", "Thumsi": "Thumsi", "Thupalli": "Thupalli", "Thyaluru": "Thyaluru",
    "Thyaranahalli": "Thyaranahalli", "Thyranahalli": "Thyranahalli", "Timmasandra": "Timmasandra",
    "Tippasandra": "Tippasandra", "Tirumanalli": "Tirumanalli", "Tokul Gatta": "Tokul Gatta",
    "Tokul Katta": "Tokul Katta", "Totle": "Totle", "Trumaladevarahatti": "Trumaladevarahatti",
    "Tumtagire": "Tumtagire", "Tylur": "Tylur", "Tylur cross": "Tylur cross", "Uddagatta": "Uddagatta",
    "Ulankallu": "Ulankallu", "Umlnayakana tandya": "Umlnayakana tandya", "Unganala": "Unganala",
    "Upasapura": "Upasapura", "Upavasapura": "Upavasapura", "Uppakunte": "Uppakunte",
    "Upparpet": "Upparpet", "Upperapete": "Upperapete", "Uppukunte": "Uppukunte", "Uragali": "Uragali",
    "Urati Agrahara": "Urati Agrahara", "Uratiagrahara": "Uratiagrahara", "Urigili": "Urigili",
    "Urugil": "Urugil", "Uruguli": "Uruguli", "V": None, "V Guttalli": "V Guttalli",
    "V kotturu": "V kotturu", "Vadadara Halli": "Vadadara Halli", "Vadagaenpali": "Vadagaenpali",
    "Vadagere": "Vadagere", "Vadageri": "Vadageri", "Vadagri": "Vadagri", "Vadagur": "Vadagur",
    "Vadaguru": "Vadaguru", "Vadalavadi": "Vadalavadi", "Vadarahalli": "Vadarahalli",
    "Vaddarahalli": "Vaddarahalli", "Vadgere": "Vadgere", "Vadgur": "Vadgur", "Vadikoturu": "Vadikoturu",
    "Vadodara Halli": "Vadodara Halli", "Vadrapalya": "Vadrapalya", "Vakkaleri": "Vakkaleri",
    "Valagamadi": "Valagamadi", "Valagernalli": "Valagernalli", "Valasagere": "Valasagere",
    "Vanarasi": "Vanarasi", "Varadapara": "Varadapara", "Varadepali": "Varadepali",
    "Varadepalli": "Varadepalli", "Varadhaganalli": "Varadhaganalli", "Vardepalli": "Vardepalli",
    "Vatrakunte": "Vatrakunte", "Veeramanahalli": "Veeramanahalli", "Veerapura": "Veerapura",
    "Veerasandra": "Veerasandra", "Veerasettahalli": "Veerasettahalli", "Vegasadara": "Vegasadara",
    "Vegasdara": "Vegasdara", "Vegmodugu": "Vegmodugu", "Vegumadugu": "Vegumadugu",
    "Velagaburre": "Velagaburre", "Velagalaburre": "Velagalaburre", "Velagalaburri": "Velagalaburri",
    "Vemagal": "Vemagal", "Vemgallu": "Vemgallu", "Vengasadra": "Vengasadra",
    "Vengasandra": "Vengasandra", "Vengsandra": "Vengsandra", "Venkatagirikota": "Venkatagirikota",
    "Venkatapalli": "Venkatapalli", "Venkatapura": "Venkatapura", "Venkatapuram": "Venkatapuram",
    "Venkatepalli": "Venkatepalli", "Venktapura": "Venktapura", "Ventakpura": "Ventakpura",
    "Verenahalli": "Verenahalli", "Vhikkavallabi": "Vhikkavallabi", "Vibhuthiyela": "Vibhuthiyela",
    "Vijalapura": "Vijalapura", "Vijiyapura": "Vijiyapura", "Virapura": "Virapura",
    "Virathiminahalli": "Virathiminahalli", "Vitapanahali": "Vitapanahali", "Vitapanahalli": "Vitapanahalli",
    "Vittapanahalli": "Vittapanahalli", "Vkota": "Vkota", "Vodrahalli": "Vodrahalli",
    "Vokkaleri": "Vokkaleri", "Vokkaleti": "Vokkaleti", "Vonaganahalli": "Vonaganahalli",
    "vadagere": "Vadagere", "vaddarahalli": "Vaddarahalli", "vengasandra": "Vengasandra",
    
    # Y: Large cluster
    "Yadahalli": "Yadahalli", "Yadhaganhalli": "Yadhaganhalli", "Yakavla": "Yakavla",
    "Yakkalakatte": "Yakkalakatte", "Yalachehalli": "Yalachehalli", "Yalachepalli": "Yalachepalli",
    "Yaladabagi": "Yaladabagi", "Yalagondahalli": "Yalagondahalli", "Yalavalli": "Yalavalli",
    "Yalavundahalli": "Yalavundahalli", "Yaluvalli": "Yaluvalli", "Yanadahalli": "Yanadahalli",
    "Yanadhihalli village": "Yanadhihalli village", "Yanandahalli": "Yanandahalli",
    "Yarabahalli": "Yarabahalli", "Yarabali": "Yarabali", "Yaraballi": "Yaraballi",
    "Yarablli": "Yarablli", "Yaragondahalli": "Yaragondahalli", "Yaramadanahalli": "Yaramadanahalli",
    "Yarapalya": "Yarapalya", "Yarappanahalli": "Yarappanahalli", "Yareikavala": "Yareikavala",
    "Yarekatte": "Yarekatte", "Yarekatteo": "Yarekatteo", "Yarekavala": "Yarekavala",
    "Yarekavla": "Yarekavla", "Yarekavls": "Yarekavls", "Yarikavala": "Yarikavala",
    "Yarikavla": "Yarikavla", "Yarkavalu": "Yarkavalu", "Yarrayyagarahalli": "Yarrayyagarahalli",
    "Yathuru": "Yathuru", "Yddalapslli": "Yddalapslli", "Yedslpalli": "Yedslpalli",
    "Yelagundahalli": "Yelagundahalli", "Yelavalli": "Yelavalli", "Yelchipaura": "Yelchipaura",
    "Yelladabagi": "Yelladabagi", "Yennandhali": "Yennandhali", "Yerehalli Doddanahatti": "Yerehalli Doddanahatti",
    "Yerekatte": "Yerekatte", "Yetthuru": "Yetthuru",
    
    # Lowercase/special
    "balendrapalli": "Balendrapalli", "tathenahali": "Tathenahali", "thippanahalli": "Thippanahalli",
    "tarireaddypalli": None, "tettu": None, "marakanamapalli": None,
    
    # Missing/Null handling
    "Na": None, "NA": None, "N/A": None, "nan": None, "None": None, "": None,
    "-": None, "no": None, "No": None,
}

block_mapping = {
    # Spelling mistakes
    "121pceduru":"Pedduru",
    "121pedhuru":"Pedduru",
    "121peduru":"Pedduru",
    "Anikere":"Anekere",
    "Anikera":"Anekere",
    "Anikere boyanapalle":"Anekere",
    "Bangarapet":"Bangarapet",
    "Bangarpet":"Bangarapet",
    "Bangarpet bangarpet":"Bangarapet",
    "Bangrapet":"Bangarapet",
    "Bedanakuppam":"Bendanakuppam",
    "Benanakuppam":"Bendanakuppam",
    "Bendanakuppam":"Bendanakuppam",
    "Boyanapalli":" Bommanapalli",
    "Bomanaplli":"Boyanapalli",
    "Cettibala":"Chittelaba ",
    "Chettibala":"Chittelaba",
    "Chettiball":"Chittelaba",
    "Kethagahalli":"Kethaganahalli ",
    "Kethaganahalli":"Kethaganahalli ",
    "Kethaganhalli":"Kethaganahalli",
    "Kirti kuppa":"Kirtikuppa",
    "Kokar":"Kolar",
    "Kolar":"Kolar",
    "Kupam":"Kuppam",
    "Kuppam":"Kuppam",
    "Kupppam":"Kuppam",
    "Kyasamballli":"Kyasamballi",
    "Mulabagilu":"Mulbagal",
    "Mulb5":"Mulbagal",
    "Mulbagal":"Mulbagal",
    "Mulubagalu":" Mulbagal",
    "Mulubagilu":"Mulbagal",
    "Mulubal":"Mulbagal",
    "Ramakuppam":"Ramakuppam",
    "Ramkupam":"Ramakuppam",
    "Ramkuppam":"Ramakuppam",
    "Setelpilli":"Settipalli ",
    "Setepalli":"Settipalli ",
    "Setepill":"Settipalli ",
    "Setepilli":"Settipalli ",
    "Settepilli":"Settipalli ",
    "Shanthipuram":"Santhipuram",
    "Shantipuram":"Santhipuram",
    "Shantipursm":"Santhipuram",
    "Shathipuram":"Santhipuram",
    "V kota":"V. Kota",
    "V. Kota":"V. Kota",
    "Vkota":"V. Kota",
    "vkota":"V. Kota",
    "Kgf": "KGF",
    "Kfg":"KGF",
    "K g f":"KGF",
    "K gf":"KGF",
    "K??":"KGF",
    "kgf": "KGF",
    "K.G.F": "KGF",
    "Kolar Gold Fields": "KGF",
    # Missing values
    "Na": None,
    "NA": None,
    "N/A": None,
    "nan": None,
    "None": None,
    "": None,
}
